swagger: "2.0"
info:
  description: "Basic Grammar Game"
  version: "1.0.0"
  title: "Basic Grammar Game"
  contact:
    email: "nikmohan81@gmail.com"
host: "localhost:9010"
basePath: ""
schemes:
- "http"
paths:
  /basic-grammar/api/quiz:
    post:
      summary: "Post a quiz attempt for evaluation"
      description: ""
      operationId: "evaluateQuiz"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Details of attempted quiz"
        required: true
        schema:
          $ref: "#/definitions/QuizResponse"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/QuizResponse"
  /basic-grammar/api/quiz/:
    get:
      summary: "Get a quiz"
      description: "Get a quiz with questions"
      operationId: "getQuiz"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/QuestionSet" 
definitions:            
  QuizResponse:
    type: "object"
    properties:
      playerId:
        type: "string"        
      answers:
        type: "array"
        items:
          $ref: '#/definitions/Answer'
  Question:
    type: "object"
    properties:
      id:
        type: "string"
      statement:
        type: "string"
      options:
        type: "array"
        items:
          type: "string"
      type:
        type: "string"
  QuestionSet:
    type: object
    properties:
      type: "array"
      items:
        $ref: '#/definitions/Question'
  Answer:
    type: "object"
    properties:
      id:
        type: "string"
      givenAnswer:
        type: "string"        
      result:
        type: "boolean"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
